services:
  valkey:
    image: valkey/valkey:alpine
    container_name: hls-transcoder-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: valkey-server --save 60 1 --loglevel warning
  
  redis-commander:
    container_name: hls-transcoder-redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:valkey:6379
    ports:
      - "8081:8081"
    depends_on:
      - valkey
    restart: unless-stopped
  
  asynqmon:
    image: hibiken/asynqmon
    container_name: hls-transcoder-asynqmon
    ports:
      - "8080:8080"
    depends_on:
      - valkey
    environment:
      - REDIS_URL=redis://valkey:6379/0
    restart: unless-stopped
  
  minio:
    image: minio/minio:latest
    container_name: hls-transcoder-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data: